# Generated by Django 3.2 on 2022-11-26 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pullrequest',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('merged', 'Merged'), ('closed', 'Closed')], default='open', max_length=64),
        ),
    ]
