# Generated by Django 3.2 on 2022-11-12 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_branch_issue_issuecomment_pullrequest_pullrequestcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='name',
            field=models.CharField(default='master', max_length=255),
            preserve_default=False,
        ),
    ]
