# Generated by Django 3.2 on 2022-11-12 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_branch_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='pullrequest',
            name='name',
            field=models.CharField(default='test', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pullrequest',
            name='repository',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.repository'),
            preserve_default=False,
        ),
    ]
