# Generated by Django 3.2 on 2022-11-12 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20221112_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='pullrequest',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('merged', 'Merged'), ('closed', 'Closed')], default='open', max_length=64),
            preserve_default=False,
        ),
    ]
