# Generated by Django 3.2 on 2022-11-13 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20221113_0856'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuecomment',
            name='repository',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.repository'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='issuecomment',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('merged', 'Merged'), ('closed', 'Closed')], default='open', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='repository',
            name='description',
            field=models.TextField(default='test'),
            preserve_default=False,
        ),
    ]
