# Generated by Django 3.2 on 2022-11-16 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20221113_1348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issuecomment',
            name='repository',
        ),
        migrations.RemoveField(
            model_name='issuecomment',
            name='status',
        ),
        migrations.AddField(
            model_name='issue',
            name='repository',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.repository'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('merged', 'Merged'), ('closed', 'Closed')], default='open', max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='branch',
            name='repository',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='api.repository'),
        ),
        migrations.AlterField(
            model_name='pullrequestcomment',
            name='pull_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='api.pullrequest'),
        ),
    ]
